#!/usr/bin/env bash
# shellcheck disable=SC2154
# Install nginX and configure a custom http header

sudo apt-get -y update
sudo apt-get -y install nginx

#setting firewall to allow request via port 80
sudo ufw allow 'Nginx HTTP'

sudo mkdir -p /var/www/html

#setting permissions to allow us to easily create files in this repo
sudo chmod -R 755 /var/www

# create the index page
echo 'Hello World!' |sudo tee /var/wwww/html/index.html

# create error 404 page
echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html

# Set redirect for a single page(/redirect_me) and add header to show hostname
string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.ella7d.tech permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Set redirect for 404 error page
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart the web server
sudo service nginx restart
