#!/usr/bin/env bash
# Install haproxy and configure the load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy

#configure HAproxy
cat << EOF > /etc/haproxy/haproxy.cfg

frontend http-in
	bind *:80
	default_backend servers

backend servers
	balance roundrobin
	server 103717-web-01 54.174.216.179:80 check 
	server 103717-web-02 18.208.119.182:80 check 
EOF

#Update hostname configuration
echo "54.174.216.179"> /etc/hostname 
echo "18.208.119.182">> /etc/hostname 

#Enable HAproxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

#HAproxy starts
/etc/init.d/haproxy start
